DESCRIPTION = "libnvidia-container"
HOMEPAGE = "https://github.com/NVIDIA/libnvidia-container"
LICENSE = "Apache-2.0"
# LIC_FILES_CHKSUM = "file://LICENSE;md5=3b83ef96387f14655fc854ddc3c6bd57"

LIC_FILES_CHKSUM = "\
    file://LICENSE;md5=3b83ef96387f14655fc854ddc3c6bd57 \
    file://deps/src/nvidia-modprobe-${NVIDIA_MODPROBE_VERSION}/modprobe-utils/nvidia-modprobe-utils.c;endline=22;md5=b6a3106a81660c726888d006853ada63 \
    file://deps/src/nvidia-modprobe-${NVIDIA_MODPROBE_VERSION}/modprobe-utils/pci-enum.h;endline=29;md5=ca948b6fabc48e616fccbf17247feebf \
    file://deps/src/nvidia-modprobe-${NVIDIA_MODPROBE_VERSION}/modprobe-utils/pci-sysfs.c;endline=25;md5=0449248350efd54938e7f8d25af965cb \
"

ELF_TOOLCHAIN_VERSION = "0.7.1"
NVIDIA_MODPROBE_VERSION = "550.54.14"
LIBTIRPC_VERSION = "1.3.4"

SRC_URI = "git://github.com/NVIDIA/libnvidia-container.git;protocol=https;name=libnvidia;branch=main \
           git://github.com/NVIDIA/nvidia-modprobe.git;protocol=https;branch=main;name=modprobe;destsuffix=git/deps/src/nvidia-modprobe-${NVIDIA_MODPROBE_VERSION} \
           file://0001-build-fix.patch \
           file://0003-fix-remove-buildpath-for-package-qa.patch \
           "

# SRCREV = "a4ef85ebc86688eeef667271abbc7cd4f1110cf6"
SRCREV_libnvidia = "86f19460fb8a72d66ed65137618321d0a7a2cde2"
# Nvidia modprobe
SRCREV_modprobe = "149440ca0654d928f27df5ebff485a122bfe43b1"
SRCREV_FORMAT = "libnvidia_modprobe"

DEPENDS = " \
            curl-native ca-certificates-native go-native \
            coreutils-native \
            pkgconfig-native \
            libcap \
            elfutils \
            libtirpc134 \
            ldconfig-native \        
            "

S = "${WORKDIR}/git"